# Generated by Django 4.1.2 on 2022-10-09 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Artist',
            fields=[
                ('stage_name', models.CharField(max_length=150, primary_key=True, serialize=False)),
                ('social_media_link', models.URLField(blank=True, default='', max_length=250)),
            ],
        ),
    ]
