# Generated by Django 4.1.2 on 2022-10-11 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('albums', '0003_alter_album_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='reviewed_by_admin',
            field=models.BooleanField(default=False, help_text='Approve the album if its name is not explicit'),
        ),
    ]
