# Generated by Django 4.1.2 on 2022-10-17 14:52

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('albums', '0005_remove_album_created_at_album_created_album_modified'),
    ]

    operations = [
        migrations.CreateModel(
            name='Song',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default=None, max_length=150)),
                ('image', models.ImageField(upload_to='songs/images/')),
                ('audio', models.FileField(upload_to='songs/audio/', validators=[django.core.validators.FileExtensionValidator(['mp3', 'wav'])])),
                ('album', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='albums.album')),
            ],
        ),
    ]
